# Generated by Django 4.2 on 2024-06-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created_date',)},
        ),
    ]
